{{- define "immich.server.api" -}}
controllers:
  {{ .name }}:
    type: deployment
    strategy: RollingUpdate
    containers:
      main:
        env:
          {{ if .root.Values.immich.metrics.enabled }}
          IMMICH_TELEMETRY_INCLUDE: all
          {{ end }}
          {{- if .root.Values.immich.configuration }}
          IMMICH_CONFIG_FILE: /config/immich-config.yaml
          {{- end }}
          IMMICH_WORKERS_INCLUDE: api
        ports:
          http:
            name: http
            containerPort: 2283
            protocol: TCP
          metrics-api:
            enabled: {{ .root.Values.immich.metrics.enabled }}
            name: metrics-api
            containerPort: 8081
            protocol: TCP
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/server/ping
                port: http
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/server/ping
                port: http
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 30

service:
  {{ .name }}:
    enabled: true
    controller: {{ .name }}
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 2283
        targetPort: http
        protocol: HTTP
      metrics-api:
        enabled: {{ .root.Values.immich.metrics.enabled }}
        port: 8081
        targetPort: metrics-api
        protocol: HTTP

serviceMonitor:
  {{ .name }}:
    enabled: {{ .root.Values.immich.metrics.enabled }}
    endpoints:
      - port: metrics-api
        scheme: http
{{- end -}}