{{- define "immich.server.microservices" -}}
controllers:
  {{ .name }}: # TODO Dynamic name from inputs
    type: deployment
    strategy: RollingUpdate
    containers:
      main:
        env:
          {{ if .root.Values.immich.metrics.enabled }}
          IMMICH_TELEMETRY_INCLUDE: all
          {{ end }}
          {{- if .root.Values.immich.configuration }}
          IMMICH_CONFIG_FILE: /config/immich-config.yaml
          {{- end }}
          IMMICH_WORKERS_INCLUDE: microservices
        ports:
          metrics-ms:
            enabled: {{ .root.Values.immich.metrics.enabled }}
            name: metrics-ms
            containerPort: 8082
            protocol: TCP
        {{/* TODO Add probes for microservices container */}}
        probes: {}

service:
  {{ .name }}:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      metrics-ms:
        enabled: {{ .root.Values.immich.metrics.enabled }}
        port: 8082
        targetPort: metrics-ms
        protocol: HTTP

serviceMonitor:
  {{ .name }}:
    enabled: {{ .root.Values.immich.metrics.enabled }}
    endpoints:
      - port: metrics-ms
        scheme: http
{{- end -}}