{{- define "immich.server.microservices" -}}
controllers:
  main: # TODO Dynamic name from inputs
    type: deployment
    strategy: RollingUpdate
    containers:
      main:
        env:
          {{ if .Values.immich.metrics.enabled }} # TODO available in template?
          IMMICH_TELEMETRY_INCLUDE: all
          {{ end }}
          {{- if .Values.immich.configuration }}
          IMMICH_CONFIG_FILE: /config/immich-config.yaml
          {{- end }}
          IMMICH_WORKERS_INCLUDE: microservices
        ports:
          {{- if .Values.immich.metrics.enabled }}
          - name: metrics-ms
            containerPort: 8082
            protocol: TCP
          {{- end }}
        probes: {} # TODO Add probes for microservices, What endpoints to use?

service:
  main:
    enabled: true
    controller: main
    primary: true
    type: ClusterIP
    ports:
      metrics-ms:
        enabled: {{ .Values.immich.metrics.enabled }}
        port: 8082
        targetPort: metrics-ms
        protocol: HTTP


serviceMonitor:
  main:
    enabled: {{ .Values.immich.metrics.enabled }}
    endpoints:
      - port: metrics-ms
        scheme: http
{{- end -}}